// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPDPFSSrxj0UM8QjJeOwqi-QjM7VoKpo',
    appId: '1:1094819422104:android:2b9b448a887f667d1655ed',
    messagingSenderId: '1094819422104',
    projectId: 'det-tonryong',
    storageBucket: 'det-tonryong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LBrOVkWogbJdv7EjTCDMqzHaIfGI3Hs',
    appId: '1:1094819422104:ios:1ca421ef4823518b1655ed',
    messagingSenderId: '1094819422104',
    projectId: 'det-tonryong',
    storageBucket: 'det-tonryong.firebasestorage.app',
    androidClientId: '1094819422104-376563ihj2ef5nadudn878nmorklk39t.apps.googleusercontent.com',
    iosClientId: '1094819422104-6qigu8rm72kfpli0b6dhfkd125kskcec.apps.googleusercontent.com',
    iosBundleId: 'com.dettonryong.app',
  );

}